### PR TITLE
Fix cmake collison of build shared and visibility issue

### PR DESCRIPTION
**Pull request by kiran1228**

### CODE REVIEW

**Review by svensht2 — APPROVED** [review]

**Comment by DillonSkeehan** [comment]
What was the build shared issue? was this separate from the exported visibility linking errors?

**Comment by kiran1228** [comment]
A lot of our dependencies have the cmake flag ‘BUILD_SHARED_LIBS’ which cases the build to be static. It is separate from the visibility.

**Comment by svensht2** [comment]
@DillonSkeehan any further comments?

**Comment by DillonSkeehan** [comment]
@svensht2 👍

**Pull request merged**
